config/routes.rb
Rails.application.routes.draw do

  resources :secret_codes
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'users', to: 'home#users'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    user.roles.each do |role|
      if role.name ==  "admin"
        can [:manage], :all
      else
        can [:manage], User
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_role_maps, :class_name => "UserRoleMap"
  has_many :users, :class_name => "User", :through => :user_role_maps
end

app/models/secret_code.rb
class SecretCode < ApplicationRecord
  require "securerandom"

  ITERATION_OPTIONS = [1,10,20,50,100]

  def self.generate_codes iterations
    codes = []
    iterations.times.each do |i|
      code = SecureRandom.hex(5).upcase
      codes << SecretCode.create!(code: code)
    end
    codes
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :secret_code
  has_many :user_role_maps, :class_name => "UserRoleMap", :primary_key => :id, :foreign_key => "user_id"
  has_many :roles, :through => :user_role_maps

  validate :secret_valid

  after_save :is_secret_valid

  def secret_valid
    @code = self.code

    if @code == "" || @code.nil?
      errors.add(:code, ": New user requires Secret Code to register. Please contact Adminstrator.")
    end
  end

  def is_secret_valid
    this_code = SecretCode.find_by_code(self.code)
    if this_code.nil?
      errors.add(:code, ": Secret Code '#{self.code}' is invalid, expired or does not exist. Please contact Adminstrator.")
      raise ActiveRecord::RecordInvalid.new(self)
    else
      this_code.user_id = self.id
      this_code.save!
    end
  end

end

app/models/user_role_map.rb
class UserRoleMap < ApplicationRecord

  belongs_to :user, :class_name => "User"
  belongs_to :role, :class_name => "Role"

  validates_presence_of :role_id, :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user! , unless: :devise_controller?

  rescue_from CanCan::AccessDenied do | exception |
    flash[:error] = exception.message
    redirect_to root_url
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first, :last, :code])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first, :last])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @secret_codes = SecretCode.all
  end

  def users
    @users = User.all
  end
end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController
  before_action :check_permissions

  def index
    @secret_codes = SecretCode.all
  end

  def create
    SecretCode.generate_codes secret_code_params[:count].to_i
    flash[:now] = secret_code_params[:count] + " secret code created successfully"
    redirect_to secret_codes_path
  end

  private

  def secret_code_params
    params.permit(:count)
  end

  def check_permissions
    authorize! :create, resource
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end

  def resource_name
    :user
  end

  def resource
    @user ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/secret_codes_helper.rb
module SecretCodesHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= fa_icon('users') %> Users Info</h5>
        <p class="text-justify">Get to explore the User List and Register new Users with option to Enable Admin Role for Users.</p>
        <p class="card-text font-weight-bold text-right">Total Users: <%= @users.size %></p>
        <%= link_to 'Explore Users', users_path, class: "btn btn-dark" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= fa_icon('shield-alt') %> Secret Code Info</h5>
        <p class="text-justify">Check out the list of all the Secret Code Available and Generate new if you have the Authority.</p>
        <p class="card-text font-weight-bold text-right">Total Codes Generated: <%= @secret_codes.size %></p>
        <%= link_to 'List Secret Codes', secret_codes_path, class: "btn btn-dark" %>
      </div>
    </div>
  </div>
</div>

app/views/home/users.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User Email</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Secret Code</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first %></td>
        <td><%= user.last %></td>
        <td><%= user.code %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Anand Padia 'Andy' | AndyMental">
    <meta name="generator" content="Rails">
    <link rel="canonical" href="<%= "#{request.protocol}#{request.host}#{request.path}" %>">
    <title>Ezref</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      .jumbotron {
        padding-top: 3rem;
        padding-bottom: 3rem;
        margin-bottom: 0;
        background-color: #fff;
      }
      @media (min-width: 768px) {
        .jumbotron {
          padding-top: 6rem;
          padding-bottom: 6rem;
        }
      }

      .jumbotron p:last-child {
        margin-bottom: 0;
      }

      .jumbotron-heading {
        font-weight: 300;
      }

      .jumbotron .container {
        max-width: 40rem;
      }

      footer {
        padding-top: 3rem;
        padding-bottom: 3rem;
      }

      footer p {
        margin-bottom: .25rem;
      }

      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <main role="main">
      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">EZRef</h1>
          <p class="lead text-muted">Project to showcase Invite Only User Registration via Secret Code. Prepared by <%= link_to 'Anand Padia "Andy"', "http://www.andymental.com" %></p>
        </div>
      </section>
      <div class="album py-5 bg-light">
        <div class="container">
          <%= render "shared/flash" %>
          <%= yield %>
        </div>
      </div>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/secret_codes/index.html.erb
<h1>Secret Codes</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Code</th>
      <th>User Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @secret_codes.each do |secret_code| %>
      <tr>
        <td><%= secret_code.code %></td>
        <% if secret_code.user_id.nil? %>
          <td> - </td>
        <% else %>
          <td><%= User.find(secret_code.user_id).email %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</br>
<%= form_with(model: @secret_code, local: true) do |form| %>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text">Secret Codes</span>
    </div>
    <%= select_tag "count", options_for_select(SecretCode::ITERATION_OPTIONS,10), class: "custom-select" %>
    <div class="input-group-append">
      <%= submit_tag 'Create', class: "btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.3/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">
    <a class="navbar-brand" href="#">EZRef</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Secret Codes', secret_codes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: "nav-link" %>
        </li>
      </ul>
      <% if user_signed_in? %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <%= link_to(fa_icon('user-times', text: "Logout"), destroy_user_session_path, method: :delete, class: "nav-link") %>
          </li>
          <li class="nav-item active">
            <%= link_to(fa_icon('users-cog', text: "Edit Account"), edit_user_registration_path, class: "nav-link") %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <%= link_to(fa_icon('user-shield', text: "Login"), new_user_session_path, class: "nav-link") %>
          </li>
          <li class="nav-item active">
            <%= link_to(fa_icon('user-tag', text: "Register"), new_user_registration_path, class: "nav-link") %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
</header>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>